name: Build & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Environment
      uses: ./.github/actions/setup-env

    - name: Build
      run: dotnet build --configuration Debug --no-incremental

    - name: Test
      run: dotnet test --no-build